// <auto-generated />
namespace HairsClientLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deletetblPatientStatuses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletetblPatientStatuses));
        
        string IMigrationMetadata.Id
        {
            get { return "201804191509430_delete tblPatientStatuses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
